# Generated by Django 4.0 on 2023-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='due',
            field=models.BooleanField(default=False),
        ),
    ]
