# Generated by Django 4.0 on 2023-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0003_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_limit',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
