# Generated by Django 4.0 on 2023-11-28 05:38

import core.event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0004_event_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.event.models.user_directory_path),
        ),
    ]
