# Generated by Django 4.0 on 2023-11-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_attending_events_user_events_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='attending_events',
            new_name='events_attending',
        ),
    ]
