# Generated by Django 4.0 on 2023-12-30 04:09

import core.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.blog.models.user_directory_path),
        ),
    ]
